$f = 'd:\Pradeep_Singh\Creations\Softwares\SSGzone\unified-login\src\TenantAdminDashboard.js'
$c = [System.IO.File]::ReadAllText($f)

$old = "            </CardContent>`n          </TabPanel>`n        </Card>`n`n        {/* Create User Dialog */}"

$new = "            </CardContent>`n          </TabPanel>`n`n          {/* Out of Office Tab */}`n          <TabPanel value={activeTab} index={4}>`n            <CardContent>`n              <Typography variant=`"h6`" sx={{ mb: 3 }}>Team Out-of-Office Status</Typography>`n              {autoresponders.length === 0 ? (`n                <Typography variant=`"body2`" color=`"text.secondary`">No active autoresponders in your team</Typography>`n              ) : (`n                <TableContainer component={Paper} variant=`"outlined`">`n                  <Table>`n                    <TableHead>`n                      <TableRow>`n                        <TableCell>Employee</TableCell>`n                        <TableCell>Subject</TableCell>`n                        <TableCell>Active Until</TableCell>`n                        <TableCell>Status</TableCell>`n                      </TableRow>`n                    </TableHead>`n                    <TableBody>`n                      {autoresponders.map((ar) => (`n                        <TableRow key={ar.id}>`n                          <TableCell>`n                            <Box>`n                              <Typography variant=`"body2`" fontWeight={600}>{ar.first_name} {ar.last_name}</Typography>`n                              <Typography variant=`"caption`" color=`"text.secondary`">{ar.user_email}</Typography>`n                            </Box>`n                          </TableCell>`n                          <TableCell>{ar.subject}</TableCell>`n                          <TableCell>{ar.end_date ? new Date(ar.end_date).toLocaleDateString() : 'Indefinite'}</TableCell>`n                          <TableCell>`n                            <Chip label={ar.is_active ? 'Active' : 'Inactive'} color={ar.is_active ? 'success' : 'default'} size=`"small`" />`n                          </TableCell>`n                        </TableRow>`n                      ))}`n                    </TableBody>`n                  </Table>`n                </TableContainer>`n              )}`n            </CardContent>`n          </TabPanel>`n        </Card>`n`n        {/* Create User Dialog */}"

$c = $c.Replace($old, $new)
[System.IO.File]::WriteAllText($f, $c)
Write-Host "Done. Contains Out of Office: $($c.Contains('Out-of-Office'))"
