server {
    listen 80;
    server_name ssgzone.in www.ssgzone.in api.ssgzone.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ssgzone.in www.ssgzone.in;
    root /opt/ssgzone/unified-login/build;
    index index.html;
    ssl_certificate /etc/letsencrypt/live/ssgzone.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ssgzone.in/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl;
    server_name api.ssgzone.in;
    ssl_certificate /etc/letsencrypt/live/ssgzone.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ssgzone.in/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location / {
        proxy_pass http://localhost:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass_header X-API-Key;
        proxy_pass_header Authorization;
    }
}
